### PR TITLE
Properly initialize this repo

### PR DESCRIPTION
**Pull request by mcmire**
Follow the instructions that we have in the module template (see "Template Instructions" in the README, which are being deleted in this commit) for new repos in order to customize the README, `package.json`, and pull request template for this repo.

Progresses #5.

### CODE REVIEW

**Review by cryptodev-2s — DISMISSED** [review]
LGTM!

**Comment by MajorLift** [comment]
Looks like there's one last sneaky `metamask-module-template`.
```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 7c87cbc..3a50bc3 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -6,4 +6,4 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ## [Unreleased]
 
-[Unreleased]: https://github.com/MetaMask/metamask-module-template/
+[Unreleased]: https://github.com/MetaMask/module-lint/
```

**Comment by MajorLift** [comment]
Looks like there's one last sneaky `metamask-module-template`.
```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 7c87cbc..3a50bc3 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -6,4 +6,4 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ## [Unreleased]
 
-[Unreleased]: https://github.com/MetaMask/metamask-module-template/
+[Unreleased]: https://github.com/MetaMask/module-lint/
```

**Review by MajorLift — APPROVED** [review]
Looks like a good start!

**Pull request merged**
